baseURL = 'https://poison.lukeorth.com/'
languageCode = 'en-us'
title = "Poison"
theme = "poison"
paginate = 10
pluralizelisttitles = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    brand = "Deadly Swords and Vile Sorcery"
    brand_image = "/images/logo-1.webp"
    # og_image = ""                             # path to social icon - front matter: image takes precedent, then og_image, then brand_url
    # publisher_icon = ""                       # path to publisher icon - defaults to favicon, used in schema
    # favicon = ""                              # path to favicon
    description = 'A sword and sorcery mod for 5E'
    dark_mode = true

    menu = [
        {Name = "Chapter", URL = "/chapter", HasChildren = true, Limit = 500},
    ]

    github_url = "https://github.com"
    
    # Plausible
    plausible = false
    
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = false
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

    # sidebar
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # light mode
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#222"          # default is #5a5a5a
    link_color = "#268bd2"          # default is #268bd2
    date_color = "#515151"          # default is #515151
    table_border_color = "#E5E5E5"  # default is #E5E5E5
    table_stripe_color = "#F9F9F9"  # default is #F9F9F9

    # dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = "#121212"   # default is #121212
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a
    table_border_color_dark = "#515151" # default is #515151
    table_stripe_color_dark = "#202020" # default is #202020


[params.meta]
    favicon = false
[taxonomies]
    series = 'series'
    tags = 'tags'
